package rs.etf.sqltranslator.codegen;

import rs.etf.sqltranslator.ast.DataType;
import rs.etf.sqltranslator.ast.StringLiteral;

/**
 * PostgreSQL renderer. Standard-conforming strings: backslash is a literal
 * character, only the single quote doubles. TINYINT and NVARCHAR never reach this
 * printer (Phase 4 narrows them) — reaching them is a contract violation.
 */
public final class PostgreSqlPrinter extends AbstractSqlPrinter {

    @Override
    protected String quoteIdentifier(String value) {
        return "\"" + value.replace("\"", "\"\"") + "\"";
    }

    @Override
    protected String renderStringLiteral(StringLiteral literal) {
        return "'" + literal.value().replace("'", "''") + "'";
    }

    @Override
    protected String concatOperator() {
        return "||";
    }

    @Override
    protected void renderDataType(DataType type) {
        String name = switch (type.type()) {
            case SMALLINT -> "SMALLINT";
            case INTEGER -> "INTEGER";
            case BIGINT -> "BIGINT";
            case DECIMAL -> "DECIMAL";
            case FLOAT -> "REAL";
            case DOUBLE -> "DOUBLE PRECISION";
            case CHAR -> "CHAR";
            case VARCHAR -> "VARCHAR";
            case TEXT -> "TEXT";
            case BOOLEAN -> "BOOLEAN";
            case DATE -> "DATE";
            case TIME -> "TIME";
            case TIMESTAMP -> "TIMESTAMP";
            case BLOB -> "BYTEA";
            case TINYINT, NVARCHAR -> throw new IllegalStateException(
                    "rule engine contract: " + type.type() + " must not reach the PG printer");
        };
        out.token(name);
        renderTypeArgs(type);
    }

    @Override
    protected void renderAutoIncrement() {
        // BY DEFAULT (not ALWAYS): permits explicit id inserts, matching
        // AUTO_INCREMENT/IDENTITY insertability — documented roadmap deviation.
        out.token("GENERATED BY DEFAULT AS IDENTITY");
    }
}
