package rs.etf.sqltranslator.codegen;

import org.junit.jupiter.api.Test;
import rs.etf.sqltranslator.core.Dialect;
import rs.etf.sqltranslator.core.TranslationOutput;
import rs.etf.sqltranslator.core.Translator;
import rs.etf.sqltranslator.core.UnsupportedFeatureException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

/**
 * Task 10: SERIAL/JSONB/UUID/BYTEA map to faithful target types; geo/vector stay refused.
 */
class PgTypesMappingTest {

    private static final String DDL = """
            CREATE TABLE t (
                id SERIAL,
                big_id BIGSERIAL,
                payload JSONB,
                meta JSON,
                guid UUID,
                bin BYTEA
            );
            """;

    @Test
    void mapsToMysql() {
        TranslationOutput out = Translator.translate(DDL, Dialect.POSTGRESQL, Dialect.MYSQL);
        assertThat(out.sql()).isEqualToNormalizingNewlines("""
                CREATE TABLE t (id INT AUTO_INCREMENT, big_id BIGINT AUTO_INCREMENT,\
                 payload JSON, meta JSON, guid CHAR(36), bin BLOB);
                """);
        assertThat(out.report().warnings()).anyMatch(w -> w.code().equals("UUID_AS_CHAR"));
    }

    @Test
    void mapsToTsql() {
        TranslationOutput out = Translator.translate(DDL, Dialect.POSTGRESQL, Dialect.TSQL);
        assertThat(out.sql()).isEqualToNormalizingNewlines("""
                CREATE TABLE t (id INT IDENTITY(1,1), big_id BIGINT IDENTITY(1,1),\
                 payload NVARCHAR(MAX), meta NVARCHAR(MAX), guid UNIQUEIDENTIFIER,\
                 bin VARBINARY(MAX));
                """);
        assertThat(out.report().warnings()).anyMatch(w -> w.code().equals("JSON_AS_NVARCHAR"));
    }

    @Test
    void mapsToPostgresNative() {
        TranslationOutput out = Translator.translate(DDL, Dialect.POSTGRESQL, Dialect.POSTGRESQL);
        assertThat(out.sql()).contains("INTEGER GENERATED BY DEFAULT AS IDENTITY");
        assertThat(out.sql()).contains("BIGINT GENERATED BY DEFAULT AS IDENTITY");
        assertThat(out.sql()).contains("JSONB");
        assertThat(out.sql()).contains("JSON");
        assertThat(out.sql()).contains("UUID");
        assertThat(out.sql()).contains("BYTEA");
    }

    @Test
    void geographyStaysRefused() {
        assertThatExceptionOfType(UnsupportedFeatureException.class)
                .isThrownBy(() -> Translator.translate(
                        "CREATE TABLE t (g GEOGRAPHY);", Dialect.POSTGRESQL, Dialect.MYSQL))
                .withMessageContaining("type GEOGRAPHY");
    }
}
