package rs.etf.sqltranslator.codegen;

import org.junit.jupiter.api.Test;
import rs.etf.sqltranslator.ast.Script;
import rs.etf.sqltranslator.core.Dialect;
import rs.etf.sqltranslator.parser.AstBuilderFacade;

import static org.assertj.core.api.Assertions.assertThat;

class PostgreSqlDdlTest {

    private String print(String sql) {
        Script script = AstBuilderFacade.buildScript(sql, Dialect.POSTGRESQL);
        return new PostgreSqlPrinter().print(script);
    }

    @Test
    void createTableWithSerialFoldsToGeneratedIdentity() {
        assertThat(print("CREATE TABLE t (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL);"))
                .isEqualTo("CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY"
                        + " PRIMARY KEY, name VARCHAR(50) NOT NULL);\n");
    }

    @Test
    void columnAttributesFollowCanonicalOrder() {
        assertThat(print("CREATE TABLE t (a INT DEFAULT 5 NOT NULL UNIQUE);"))
                .isEqualTo("CREATE TABLE t (a INTEGER NOT NULL DEFAULT 5 UNIQUE);\n");
    }

    @Test
    void tableConstraintsRender() {
        assertThat(print("CREATE TABLE t (a INT, b INT,"
                + " CONSTRAINT pk_t PRIMARY KEY (a),"
                + " FOREIGN KEY (b) REFERENCES u (id));"))
                .isEqualTo("CREATE TABLE t (a INTEGER, b INTEGER,"
                        + " CONSTRAINT pk_t PRIMARY KEY (a),"
                        + " FOREIGN KEY (b) REFERENCES u (id));\n");
    }

    @Test
    void columnReferencesClause() {
        assertThat(print("CREATE TABLE t (b INT REFERENCES u (id));"))
                .isEqualTo("CREATE TABLE t (b INTEGER REFERENCES u (id));\n");
    }

    @Test
    void dropAndAlter() {
        assertThat(print("DROP TABLE IF EXISTS t;"
                + "ALTER TABLE t ADD COLUMN c VARCHAR(10);"
                + "ALTER TABLE t DROP COLUMN c;"))
                .isEqualTo("DROP TABLE IF EXISTS t;\n"
                        + "ALTER TABLE t ADD COLUMN c VARCHAR(10);\n"
                        + "ALTER TABLE t DROP COLUMN c;\n");
    }

    @Test
    void decimalKeepsPrecisionAndScale() {
        assertThat(print("CREATE TABLE t (p DECIMAL(10,2));"))
                .isEqualTo("CREATE TABLE t (p DECIMAL(10,2));\n");
    }
}
