package rs.etf.sqltranslator.codegen;

import org.junit.jupiter.api.Test;
import rs.etf.sqltranslator.core.Dialect;
import rs.etf.sqltranslator.core.TranslationOutput;

import static org.assertj.core.api.Assertions.assertThat;
import static rs.etf.sqltranslator.codegen.CodegenTestSupport.printTranslated;

/** Through-rules printer contracts — parse → RuleEngine → print. */
class ThroughRulesPrinterTest {

    @Test
    void tsqlTopBecomesPostgresLimitWithSynthesizedNulls() {
        TranslationOutput out = printTranslated(
                "SELECT TOP 3 name FROM users ORDER BY id;",
                Dialect.TSQL, Dialect.POSTGRESQL);
        assertThat(out.sql()).isEqualTo(
                "SELECT name FROM users ORDER BY id NULLS FIRST LIMIT 3;\n");
    }

    @Test
    void postgresConcatLowersToMysqlConcatCall() {
        TranslationOutput out = printTranslated(
                "SELECT a || b FROM t;",
                Dialect.POSTGRESQL, Dialect.MYSQL);
        assertThat(out.sql()).isEqualTo("SELECT CONCAT(a, b) FROM t;\n");
    }

    @Test
    void mysqlLimitBecomesTsqlTopAndBooleanLiteralNarrows() {
        TranslationOutput out = printTranslated(
                "SELECT TRUE FROM t LIMIT 2;",
                Dialect.MYSQL, Dialect.TSQL);
        assertThat(out.sql()).isEqualTo("SELECT TOP (2) 1 FROM t;\n");
    }

    @Test
    void postgresAlwaysIdentityNormalizesToByDefaultIncludingSameDialect() {
        // ROADMAP Phase 5 policy: insertable form only; ALWAYS is not preserved.
        TranslationOutput out = printTranslated(
                "CREATE TABLE t (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY);",
                Dialect.POSTGRESQL, Dialect.POSTGRESQL);
        assertThat(out.sql()).isEqualTo(
                "CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);\n");
    }

    @Test
    void postgresTextNarrowsBeforeTsqlPrint() {
        TranslationOutput out = printTranslated(
                "CREATE TABLE t (n TEXT);",
                Dialect.POSTGRESQL, Dialect.TSQL);
        assertThat(out.sql()).isEqualTo("CREATE TABLE t (n NVARCHAR(MAX));\n");
    }

    @Test
    void postgresNullsOrderingDropsWithWarningTowardMysql() {
        TranslationOutput out = printTranslated(
                "SELECT a FROM t ORDER BY a NULLS LAST;",
                Dialect.POSTGRESQL, Dialect.MYSQL);
        assertThat(out.sql()).isEqualTo("SELECT a FROM t ORDER BY a;\n");
        assertThat(out.report().warnings())
                .anyMatch(w -> w.code().equals("NULLS_ORDERING_DROPPED"));
    }

    @Test
    void tsqlNationalStringDropsNPrefixTowardMysql() {
        TranslationOutput out = printTranslated(
                "SELECT N'café';",
                Dialect.TSQL, Dialect.MYSQL);
        assertThat(out.sql()).isEqualTo("SELECT 'café';\n");
    }
}
