package rs.etf.sqltranslator.parser;

import org.junit.jupiter.api.Test;
import rs.etf.sqltranslator.codegen.CodegenTestSupport;
import rs.etf.sqltranslator.core.Dialect;

import static org.assertj.core.api.Assertions.assertThat;

class IdentityColumnTest {

    @Test
    void pgGeneratedIdentityBecomesMysqlAutoIncrement() {
        assertThat(CodegenTestSupport.printTranslated(
                "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL)",
                Dialect.POSTGRESQL, Dialect.MYSQL).sql())
                .containsIgnoringCase("AUTO_INCREMENT");
    }

    @Test
    void tsqlIdentityBecomesPgSerialFamily() {
        assertThat(CodegenTestSupport.printTranslated(
                "CREATE TABLE t (id INTEGER PRIMARY KEY IDENTITY)",
                Dialect.TSQL, Dialect.POSTGRESQL).sql())
                .containsIgnoringCase("SERIAL");
    }

    @Test
    void smallserialFolds() {
        assertThat(CodegenTestSupport.printTranslated(
                "CREATE TABLE t (id SMALLSERIAL NOT NULL)",
                Dialect.POSTGRESQL, Dialect.TSQL).sql())
                .containsIgnoringCase("IDENTITY");
    }
}
